### PR TITLE
jump, fall, land hurtboxes

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by flip40** [comment]
Made a quick update, the new fields you added are now visible in the editor. Have you done the hurtbox polygon collider prefabs yet? If not we need those added (a folder for each animation) as well as adding them to the hurtbox arrays.

**Comment by flip40** [comment]
Made a quick update, the new fields you added are now visible in the editor. Have you done the hurtbox polygon collider prefabs yet? If not we need those added (a folder for each animation) as well as adding them to the hurtbox arrays.

**Comment by flip40** [comment]
Made a quick update, the new fields you added are now visible in the editor. Have you done the hurtbox polygon collider prefabs yet? If not we need those added (a folder for each animation) as well as adding them to the hurtbox arrays. Then we need to update the Sanji prefab so it has those changes (don't forget to enable the prefab before you drag it down, I always forget that and have to copy it to the prefab again).

**Comment by ghost** [comment]
Oh I forgot to add the the new prefabs. Will update this in a bit. Along with updating the Sanji prefab

**Comment by ghost** [comment]
Added the new prefabs

**Comment by flip40** [comment]
Added Sanji prefab and fixed land2 (used wrong sprite). Looks good now, going to merge.

**Pull request merged**
